SET NAMES UTF8;
DROP DATABASE IF EXISTS mtl;
CREATE DATABASE mtl CHARSET=UTF8;
USE mtl;

-- login
CREATE TABLE mtl_login(
    uid INT PRIMARY KEY AUTO_INCREMENT,
    phone VARCHAR(16),

);
INSERT INTO mtl_login VALUES(null,'18980812073');